/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpDataforseoApiKeyRouteImport } from './routes/help/dataforseo-api-key'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as PProjectIdRouteRouteImport } from './routes/p/$projectId/route'
import { Route as PProjectIdIndexRouteImport } from './routes/p/$projectId/index'
import { Route as PProjectIdSavedRouteImport } from './routes/p/$projectId/saved'
import { Route as PProjectIdKeywordsRouteImport } from './routes/p/$projectId/keywords'
import { Route as PProjectIdDomainRouteImport } from './routes/p/$projectId/domain'
import { Route as PProjectIdBacklinksRouteImport } from './routes/p/$projectId/backlinks'
import { Route as PProjectIdAuditRouteImport } from './routes/p/$projectId/audit'
import { Route as PProjectIdAiRouteImport } from './routes/p/$projectId/ai'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PProjectIdAuditIndexRouteImport } from './routes/p/$projectId/audit/index'
import { Route as PProjectIdAuditIssuesResultIdRouteImport } from './routes/p/$projectId/audit/issues/$resultId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDataforseoApiKeyRoute = HelpDataforseoApiKeyRouteImport.update({
  id: '/help/dataforseo-api-key',
  path: '/help/dataforseo-api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const PProjectIdRouteRoute = PProjectIdRouteRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdSavedRoute = PProjectIdSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdKeywordsRoute = PProjectIdKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdDomainRoute = PProjectIdDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdBacklinksRoute = PProjectIdBacklinksRouteImport.update({
  id: '/backlinks',
  path: '/backlinks',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdAuditRoute = PProjectIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdAiRoute = PProjectIdAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdAuditIndexRoute = PProjectIdAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdAuditRoute,
} as any)
const PProjectIdAuditIssuesResultIdRoute =
  PProjectIdAuditIssuesResultIdRouteImport.update({
    id: '/issues/$resultId',
    path: '/issues/$resultId',
    getParentRoute: () => PProjectIdAuditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/help/dataforseo-api-key': typeof HelpDataforseoApiKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$projectId/ai': typeof PProjectIdAiRoute
  '/p/$projectId/audit': typeof PProjectIdAuditRouteWithChildren
  '/p/$projectId/backlinks': typeof PProjectIdBacklinksRoute
  '/p/$projectId/domain': typeof PProjectIdDomainRoute
  '/p/$projectId/keywords': typeof PProjectIdKeywordsRoute
  '/p/$projectId/saved': typeof PProjectIdSavedRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/audit/': typeof PProjectIdAuditIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof PProjectIdAuditIssuesResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/help/dataforseo-api-key': typeof HelpDataforseoApiKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$projectId/ai': typeof PProjectIdAiRoute
  '/p/$projectId/backlinks': typeof PProjectIdBacklinksRoute
  '/p/$projectId/domain': typeof PProjectIdDomainRoute
  '/p/$projectId/keywords': typeof PProjectIdKeywordsRoute
  '/p/$projectId/saved': typeof PProjectIdSavedRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
  '/p/$projectId/audit': typeof PProjectIdAuditIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof PProjectIdAuditIssuesResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/p/$projectId': typeof PProjectIdRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/help/dataforseo-api-key': typeof HelpDataforseoApiKeyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$projectId/ai': typeof PProjectIdAiRoute
  '/p/$projectId/audit': typeof PProjectIdAuditRouteWithChildren
  '/p/$projectId/backlinks': typeof PProjectIdBacklinksRoute
  '/p/$projectId/domain': typeof PProjectIdDomainRoute
  '/p/$projectId/keywords': typeof PProjectIdKeywordsRoute
  '/p/$projectId/saved': typeof PProjectIdSavedRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/audit/': typeof PProjectIdAuditIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof PProjectIdAuditIssuesResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$projectId'
    | '/sign-in'
    | '/sign-up'
    | '/help/dataforseo-api-key'
    | '/api/auth/$'
    | '/p/$projectId/ai'
    | '/p/$projectId/audit'
    | '/p/$projectId/backlinks'
    | '/p/$projectId/domain'
    | '/p/$projectId/keywords'
    | '/p/$projectId/saved'
    | '/p/$projectId/'
    | '/p/$projectId/audit/'
    | '/p/$projectId/audit/issues/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/help/dataforseo-api-key'
    | '/api/auth/$'
    | '/p/$projectId/ai'
    | '/p/$projectId/backlinks'
    | '/p/$projectId/domain'
    | '/p/$projectId/keywords'
    | '/p/$projectId/saved'
    | '/p/$projectId'
    | '/p/$projectId/audit'
    | '/p/$projectId/audit/issues/$resultId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/p/$projectId'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/help/dataforseo-api-key'
    | '/api/auth/$'
    | '/p/$projectId/ai'
    | '/p/$projectId/audit'
    | '/p/$projectId/backlinks'
    | '/p/$projectId/domain'
    | '/p/$projectId/keywords'
    | '/p/$projectId/saved'
    | '/p/$projectId/'
    | '/p/$projectId/audit/'
    | '/p/$projectId/audit/issues/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PProjectIdRouteRoute: typeof PProjectIdRouteRouteWithChildren
  HelpDataforseoApiKeyRoute: typeof HelpDataforseoApiKeyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/dataforseo-api-key': {
      id: '/help/dataforseo-api-key'
      path: '/help/dataforseo-api-key'
      fullPath: '/help/dataforseo-api-key'
      preLoaderRoute: typeof HelpDataforseoApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/saved': {
      id: '/p/$projectId/saved'
      path: '/saved'
      fullPath: '/p/$projectId/saved'
      preLoaderRoute: typeof PProjectIdSavedRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/keywords': {
      id: '/p/$projectId/keywords'
      path: '/keywords'
      fullPath: '/p/$projectId/keywords'
      preLoaderRoute: typeof PProjectIdKeywordsRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/domain': {
      id: '/p/$projectId/domain'
      path: '/domain'
      fullPath: '/p/$projectId/domain'
      preLoaderRoute: typeof PProjectIdDomainRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/backlinks': {
      id: '/p/$projectId/backlinks'
      path: '/backlinks'
      fullPath: '/p/$projectId/backlinks'
      preLoaderRoute: typeof PProjectIdBacklinksRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/audit': {
      id: '/p/$projectId/audit'
      path: '/audit'
      fullPath: '/p/$projectId/audit'
      preLoaderRoute: typeof PProjectIdAuditRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/ai': {
      id: '/p/$projectId/ai'
      path: '/ai'
      fullPath: '/p/$projectId/ai'
      preLoaderRoute: typeof PProjectIdAiRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/audit/': {
      id: '/p/$projectId/audit/'
      path: '/'
      fullPath: '/p/$projectId/audit/'
      preLoaderRoute: typeof PProjectIdAuditIndexRouteImport
      parentRoute: typeof PProjectIdAuditRoute
    }
    '/p/$projectId/audit/issues/$resultId': {
      id: '/p/$projectId/audit/issues/$resultId'
      path: '/issues/$resultId'
      fullPath: '/p/$projectId/audit/issues/$resultId'
      preLoaderRoute: typeof PProjectIdAuditIssuesResultIdRouteImport
      parentRoute: typeof PProjectIdAuditRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PProjectIdAuditRouteChildren {
  PProjectIdAuditIndexRoute: typeof PProjectIdAuditIndexRoute
  PProjectIdAuditIssuesResultIdRoute: typeof PProjectIdAuditIssuesResultIdRoute
}

const PProjectIdAuditRouteChildren: PProjectIdAuditRouteChildren = {
  PProjectIdAuditIndexRoute: PProjectIdAuditIndexRoute,
  PProjectIdAuditIssuesResultIdRoute: PProjectIdAuditIssuesResultIdRoute,
}

const PProjectIdAuditRouteWithChildren = PProjectIdAuditRoute._addFileChildren(
  PProjectIdAuditRouteChildren,
)

interface PProjectIdRouteRouteChildren {
  PProjectIdAiRoute: typeof PProjectIdAiRoute
  PProjectIdAuditRoute: typeof PProjectIdAuditRouteWithChildren
  PProjectIdBacklinksRoute: typeof PProjectIdBacklinksRoute
  PProjectIdDomainRoute: typeof PProjectIdDomainRoute
  PProjectIdKeywordsRoute: typeof PProjectIdKeywordsRoute
  PProjectIdSavedRoute: typeof PProjectIdSavedRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
}

const PProjectIdRouteRouteChildren: PProjectIdRouteRouteChildren = {
  PProjectIdAiRoute: PProjectIdAiRoute,
  PProjectIdAuditRoute: PProjectIdAuditRouteWithChildren,
  PProjectIdBacklinksRoute: PProjectIdBacklinksRoute,
  PProjectIdDomainRoute: PProjectIdDomainRoute,
  PProjectIdKeywordsRoute: PProjectIdKeywordsRoute,
  PProjectIdSavedRoute: PProjectIdSavedRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
}

const PProjectIdRouteRouteWithChildren = PProjectIdRouteRoute._addFileChildren(
  PProjectIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PProjectIdRouteRoute: PProjectIdRouteRouteWithChildren,
  HelpDataforseoApiKeyRoute: HelpDataforseoApiKeyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
